require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'GoogleSignIn', '~> 5.0.2'

target 's325a2new' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  # add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  target 's325a2newTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 's325a2new-tvOS' do
  # Pods for s325a2new-tvOS

  target 's325a2new-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
